# Generated by Django 3.0.8 on 2020-07-31 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Аватарка')),
                ('slogan', models.TextField(blank=True, verbose_name='Слоган')),
                ('work_hours', models.CharField(max_length=250, verbose_name='Часы работы')),
                ('address', models.CharField(max_length=250, verbose_name='Адрес')),
                ('fon', models.CharField(max_length=250, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Данные компании',
            },
        ),
    ]
