# Generated by Django 3.0.8 on 2020-07-31 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooldoctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='header',
            options={'verbose_name': 'Данные компании', 'verbose_name_plural': 'Данные компании'},
        ),
        migrations.AlterField(
            model_name='header',
            name='work_hours',
            field=models.TextField(max_length=250, verbose_name='Часы работы'),
        ),
    ]
