# Generated by Django 3.0.8 on 2020-08-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooldoctor', '0003_auto_20200731_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='title',
            field=models.CharField(default='Cool', max_length=250, verbose_name='Название'),
        ),
    ]
