# Generated by Django 3.0.8 on 2020-08-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooldoctor', '0008_auto_20200806_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Аватарка')),
            ],
            options={
                'verbose_name': 'Аватарка',
                'verbose_name_plural': 'Аватарки',
            },
        ),
        migrations.RemoveField(
            model_name='topmenu',
            name='avatar',
        ),
    ]
